#!/bin/tcsh -xef
#script generated by the command:
#

set ddir = '../out/afni/subject_results/group.young'
set scrdir = `pwd`

set sids = ( `cat $1` )



foreach s ($sids)
	set ss = (`printf "%04d" $s`)

	./run_suma_ana.sh $ss

	set sdir = $ddir/subj.sub{$ss}
	cd $sdir
	rm -R sub{$ss}.suma.results
	./proc.suma.sub{$ss}
	cd $scrdir

end	