#!/bin/tcsh -xef
#script generated by the command:
#
set droot = /media/DATA2/GripForce
set subid1 = $1
set subid2 = sub{$subid1}
set subid3 = sub-{$subid1}
set out_root = $droot/out/afni/subject_results/group.young
#set regstimorder = $2
set preproc_dir = $droot/out/fmriprep
set extrfile1 = $preproc_dir/sub-{$subid1}/ses-01/func/{$subid3}_ses-01_task-GFORCE_run-1_desc-confounds_sel_timeseries.1D
set extrfile2 = $preproc_dir/sub-{$subid1}/ses-01/func/{$subid3}_ses-01_task-GFORCE_run-2_desc-confounds_sel_timeseries.1D
set extrfile = $preproc_dir/sub-{$subid1}/ses-01/func/{$subid3}_ses-01_task-GFORCE_desc-confounds_sel_timeseries.1D


#set extralab = `head -1 $extrfile`

if  ! ( -d $out_root/subj.$subid2) then
    #echo output dir "$subj.results" already exists
    mkdir $out_root/subj.$subid2
    #mkdir $out_root/subj.$subid2/$subid2.results
endif


set regstilab = "R40 R60 L40 L60 "

endif

afni_proc.py -subj_id sub$subid1.CSPLIN -script proc.CSPLIN.sub$subid1 -scr_overwrite -blocks                                                                     \
    mask blur regress -copy_anat                                                                                                              \
    $preproc_dir/$subid3/ses-01/anat/{$subid3}_ses-01_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii.gz                    \
    -dsets                                                                                                                                    \
    $preproc_dir/$subid3/ses-01/func/{$subid3}_ses-01_task-GFORCE_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz \
    $preproc_dir/$subid3/ses-01/func/{$subid3}_ses-01_task-GFORCE_run-2_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz \
    -tcat_remove_first_trs 0 -blur_size 4.0 -regress_stim_times                                                                               \
    $droot/beh/{$subid3}_ses-01_task-GFORCE_run-01-40%.1D                                                                        \
    $droot/beh/{$subid3}_ses-01_task-GFORCE_run-01-60%.1D                                                                        \
    $droot/beh/{$subid3}_ses-01_task-GFORCE_run-02-40%.1D                                                                        \
    $droot/beh/{$subid3}_ses-01_task-GFORCE_run-02-60%.1D                                                                        \
    -regress_stim_labels $regstilab -regress_basis 'CSPLINzero(0, 24, 21)'\
    -regress_extra_stim_files $extrfile\
    -regress_extra_stim_labels non_interest\
    -regress_opts_3dD \
    -jobs 20 -num_glt 11 -gltsym 'SYM: L60 -L40'                                                                           \
    -glt_label 1 L60-L40 -gltsym 'SYM: R60 -R40' -glt_label 2 R60-R40                                                                        \
    -gltsym 'SYM: L40 +L60 -R60 -R40' -glt_label 3 L-R -gltsym 'SYM: L60                                                                   \
    +R60 -L40 -R40' -glt_label 4 60-40 -gltsym 'SYM: L40 +L60'                                                                            \
    -glt_label 5 L -gltsym 'SYM: R40 +R60' -glt_label 6 R -gltsym 'SYM:                                                                      \
    L40 +R40' -glt_label 7 40 -gltsym 'SYM: L60 +R60' -glt_label 8 60                                                                       \
    -gltsym 'SYM: R40 +R60 -L40 -L60' -glt_label 9 R-L -gltsym 'SYM: R60                                                                   \
    -R40 -L60 +L40' -glt_label 10 int1 -gltsym 'SYM: L60 -L40 -R60 +R40'                                                                    \
    -glt_label 11 int2 -regress_compute_fitts                                                                         \
    -regress_make_ideal_sum sum_ideal.1D -regress_est_blur_epits                                                                              \
    -regress_est_blur_errts \
    -mask_apply epi \
    -regress_censor_outliers 0.15 \
    -regress_reml_exec


# -regress_local_times                                                                                                        \                                                                                                                \
 
#-regress_apply_mot_types demean deriv -regress_motion_per_run                                                                             \



mv proc.CSPLIN.sub$subid1 $out_root/subj.$subid2
