#!/bin/tcsh -ef
#script generated by the command:


# Check if the number of arguments is less than 2
if ($#argv < 2) then
    echo 
    echo "Error: This script requires at least 2 arguments."
    echo
    echo "Usage: ./run_afni_model_many.sh <subjid.txt> <sesid>"
    echo "subjid.txt: the file whose each row is a subject's numerical id"
    echo "sesid: the session ID"
    echo 
    exit 1  # Exit with a non-zero status to indicate an error
endif






#refering to :
# https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dDeconvolve.html



set bfunc = CSPLINzero  #name of the model
set bparam = '(-4.8,16.8,10)'  #model parameter




#set sids = (1 2 3 5 6 9 11 12 13 15 16 17 18 19 21 22 23 24 25 26 29 30 31 34 45 46 48 49 56 57 63 82)
set sids = `cat $1 | awk -F "," '{ print $1 }'`
set ses = $2


set ddir = ../out/afni/subject_results
set scrdir = `pwd`

#set sids = (59)
foreach s ($sids)
	#set ss = (`printf "%04d" $s`)
	set ss = $s

	../preproc_scripts/run_afni_model_$ses.sh $ss $bfunc $bparam $ses
	set sdir = $ddir/subj.sub{$ss}/$ses
	echo $sdir

 
	cd $sdir
	./proc.$bfunc.sub{$ss}
	cd $scrdir



end
