#!/bin/tcsh -ef
#script generated by the command:

# Check if the number of arguments is less than 4
if ($#argv < 4) then
    echo 
    echo "Error: This script requires at least 4 arguments."
    echo
    echo "Usage: ./run_afni_model.sh <subjid> <bf> <bfparam> <sesid>"
    echo "subjid: the 4 digit subject id"
    echo "bf: basis function, e.g., CSPLINzero, TENT"
    echo "bparam: paramters of basis function, eg. '(-4.8,16.8,10)'"
    echo "sesid: the session ID (ses-01 or ses-02)"
    echo
    echo "Example: ./run_afni_model.sh 0001 CSPLINzero '(-4.8,16.8,10)' ses-02"
    echo 
    exit 1  # Exit with a non-zero status to indicate an error
endif

set droot = /media/DATA3/GripForce

# modify due to connections to dropbox 20231006; oringinal: set fproot = /media/DATA3/GripForce
# set fproot = /home/aclexp/Dropbox/fmriprep_out

# 20231007 by EC
# change back to the original data folder after fix the file backing up problem
#set fproot = /media/DATA3/GripForce
set fproot = "/home/aclexp/TCNL_Dropbox/tcnl_tcnl/fmriprep_out"
#set fproot = "/home/aclexp/Dropbox/fmriprep_out"
set subid1 = $1
set subid2 = sub{$subid1}
set subid3 = sub-{$subid1}
set out_root = $droot/out/afni/subject_results
#set regstimorder = $2
set preproc_dir = "$fproot"/fmriprep
set bfunc = $2
set bparam = $3
set ses = $4

#set extrfile = "$preproc_dir"/sub-{$subid1}/{$ses}/func/{$subid3}_{$ses}_task-GFORCE_desc-confounds_sel_timeseries.1D

set model = (`printf "%s%s" $bfunc $bparam`)
echo $model
set non_interest = (`cat ../preproc_scripts/confound_labels.txt`)


#set extralab = `head -1 $extrfile`

if  ! ( -d $out_root/subj.$subid2) then
    #echo output dir "$subj.results" already exists
    mkdir $out_root/subj.$subid2

endif

# Ensure the session directory exists within the subject's directory
if (! -d $out_root/subj.$subid2/$ses) then
    mkdir -p $out_root/subj.$subid2/$ses
endif


if  ( -d $out_root/subj.$subid2/$ses/$subid2.$model.results) then
    echo "output dir $subj.$model.results already exists"
    rm -R $out_root/subj.$subid2/$subid2.$model.results

endif



set extrfile = "$preproc_dir"/sub-{$subid1}/${ses}/func/{$subid3}_${ses}_task-GFORCE_desc-confounds_sel_timeseries.1D


set regstilab = "R40 R60 L40 L60 "

endif

afni_proc.py -subj_id sub$subid1.$bfunc \
    -script $out_root/subj.$subid2/$ses/proc.$bfunc.sub$subid1 \
    -scr_overwrite \
    -blocks  mask blur regress \
    #-write_3dD_script $out_root/subj.sub$subid1/proc.{$bfunc}.sub$subid1.3dD \
	  #-write_3dD_prefix GLM \
    -copy_anat  "$preproc_dir/$subid3/$ses/anat/${subid3}_${ses}_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii.gz"                    \
    -dsets                                                                                                                                    \
    "$preproc_dir/$subid3/$ses/func/${subid3}_${ses}_task-GFORCE_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz" \
    "$preproc_dir/$subid3/$ses/func/${subid3}_${ses}_task-GFORCE_run-2_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz" \
    -tcat_remove_first_trs 0 -blur_size 4.0 -regress_stim_times                                                                               \
    $droot/beh/${ses}/{$subid3}_${ses}_task-GFORCE_run-01-40%.1D                                                                        \
    $droot/beh/${ses}/{$subid3}_${ses}_task-GFORCE_run-01-60%.1D                                                                        \
    $droot/beh/${ses}/{$subid3}_${ses}_task-GFORCE_run-02-40%.1D                                                                        \
    $droot/beh/${ses}/{$subid3}_${ses}_task-GFORCE_run-02-60%.1D                                                                        \
    #-regress_stim_labels $regstilab -regress_basis "'$bfunc$bparam'"\
    -regress_stim_labels $regstilab -regress_basis $model \
    -regress_extra_ortvec $extrfile\
    -regress_extra_ortvec_labels no_interest \
    -regress_opts_3dD -polort 'A'\
    -jobs 20 -num_glt 11 \
    -gltsym 'SYM: L60[3..6] -L40[3..6]' -glt_label 1 L60-L40 \
    -gltsym 'SYM: R60[3..6] -R40[3..6]' -glt_label 2 R60-R40  \
    -gltsym 'SYM: L40[3..6] +L60[3..6] -R60[3..6] -R40[3..6]' -glt_label 3 L-R \
    -gltsym 'SYM: L60[3..6] +R60[3..6] -L40[3..6] -R40[3..6]' -glt_label 4 60-40 \
    -gltsym 'SYM: -1*L60[0..2] +1*L60[3..6]' -glt_label 5 L60_all \
    -gltsym 'SYM: -1*R60[0..2] +1*R60[3..6]' -glt_label 6 R60_all \
    -gltsym 'SYM: -1*L40[0..2] +1*L40[3..6]' -glt_label 7 L40_all \
    -gltsym 'SYM: -1*R40[0..2] +1*R40[3..6]' -glt_label 8 R40_all \
    -gltsym 'SYM: R40[3..6] +R60[3..6] -L40[3..6] -L60[3..6]' -glt_label 9 R-L \
    -gltsym 'SYM: R60[3..6] -R40[3..6] -L60[3..6] +L40[3..6]' -glt_label 10 int1 \
    -regress_compute_fitts   \
    -regress_make_ideal_sum sum_ideal.1D -regress_est_blur_epits                                                                              \
    -regress_est_blur_errts \
    -mask_apply epi \
    -regress_censor_outliers 0.15\
    -regress_reml_exec

#mv $out_root/subj.sub$subid1/proc.{$bfunc}.sub$subid1.3dD sub$subid1.{$bfunc}.results/

    #    -regress_extra_ortvec_labels test \
