#!/bin/tcsh -xef
#script generated by the command:
#

set ddir = '../out/afni/subject_results'
set scrdir = `pwd`

#refering to :
# https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dDeconvolve.html

set bfunc = CSPLIN  #name of the model
set bparam = '(-4.8,16.8,10)'  #model parameter

set sids = `cat $1 | awk -F "," '{ print $1 }'`
foreach s ($sids)
	set ss = $s


	set sdir = $ddir/subj.sub{$ss}
	echo $sdir

	if (-d $sdir/sub{$ss}.$bfunc.results) then
		rm -R $sdir/sub{$ss}.$bfunc.results
	endif
	cd $sdir
	./proc.$bfunc.sub{$ss}

end
