#!/bin/tcsh -xef
#script generated by the command:
#

set ddir = '../out/afni/subject_results/group.young'
set scrdir = `pwd`
#set sids = (1 2 3 5 9 11 12 15 16 17 18 19 21 22 23 24 25 26 29 30 31 45 46 48 49 56 57)
set sids = ( 1)

foreach s ($sids)
	set ss = (`printf "%04d" $s`)
	

	# if !(-d ../out/afni/sub-$ss) then
	# 	cp -R ../out/fmriprep/sub-$ss ../out/afni
	# endif 


	./run_afni_tent.sh $ss 
	set sdir = $ddir/subj.sub{$ss}
	cd $sdir

	if (-d sub{$ss}.tent.results) then
		rm -R sub{$ss}.tent.results
	endif
	./proc.tent.sub{$ss}
	cd $scrdir



end	
