#!/bin/tcsh -xef
#script generated by the command:
#

set ddir = '../out/afni/subject_results/group.young'
set scrdir = `pwd`
#set sids = (2 9 11 16 17 18 19 21 22 26)
set sids = (49)

foreach s ($sids)
	set ss = (`printf "%04d" $s`)
	if (-d $fs_data/sub-$ss/surf/SUMA ) then
		rm -R $fs_data/sub-$ss/surf/SUMA
	endif
	./prep_suma.sh $ss 1


end	